# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(text: "Changelog: ")
    # Ensure that your git status is not dirty
    increment_build_number(
      build_number: latest_testflight_build_number + 1,  
      xcodeproj: "OSLEventApp.xcodeproj")
    # Commit the version bump
    commit_version_bump(xcodeproj: "OSLEventApp.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote
    
    build_app(workspace: "OSLEventApp.xcworkspace", scheme: "OSLEventApp")
    changelog_from_git_commits # generate the changelog based on your last commits
    
    upload_to_testflight(changelog: changelog)
  end

  desc "Push a new release build to the App Store"
  lane :release do
    get_certificates
    get_provisioning_profile

    increment_build_number(
      build_number: latest_testflight_build_number + 1,  
      xcodeproj: "OSLEventApp.xcodeproj")
    gym(scheme: 'OSLEventApp', workspace: 'OSLEventApp.xcworkspace')
    deliver(
      force: true,
      reject_if_possible: true,
      skip_metadata: false,
      submit_for_review: true,
      automatic_release: true,
      submission_information: {
        add_id_info_uses_idfa: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_install: true,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: true,
        export_compliance_encryption_updated: false,
      }
    )
    commit_version_bump(message: 'bump build')
    push_to_git_remote
    slack(message: "Successfully uploaded a new App Store build")
    end
end
